import type { Ticket } from "@data/tickets";

export const tickets: {
  name: string;
  ticket: Ticket;
}[] = [
  {
    name: "New",
    ticket: {
      Created: new Date(2025, 8, 1),
      Number: 10001,
      _id: "new-1",
      "Ticket Status": "New",
      Resolution: "User Education",
      Priority: 2,
      History: JSON.stringify({ entries: [] }),
      // Only one Temporary Device and SubmittedBy per ticket
      FormID: "FORM-NEW",
      "User Description": "Brand new ticket, nothing done yet.",
      "Device Status": undefined,
      "Temp Status": undefined,
      "Form Name": "Alice Example",
      FormEmail: "alice@example.com",
      FormAsset: "22222",
      Notes: "Initial notes.",
      PrivateNotes: "Private info.",
      "Repair Cost": 0,
      Student: ["stu-222222"],
      Device: ["asset-2"],
      // Only one Temporary Device and SubmittedBy per ticket
      _linked: {
        Device: {
          "Asset Tag": "22222",
          "Device Type": "Chromebook",
          Location: "ICHS - Cart 2",
          // No Status field in Asset type
          _id: "asset-2",
        },
        Student: {
          Name: "Alice Example",
          LASID: 222222,
          YOG: "2027",
          Advisor: "Bob Advisor",
          Email: "alice@example.com",
        },
      },
    },
  },
  {
    name: "Awaiting Drop-Off",
    ticket: {
      Created: new Date(2025, 8, 2),
      Number: 10002,
      _id: "dropoff-1",
      "Ticket Status": "Awaiting Drop-Off",
      Resolution: "User Education",
      Priority: 2,
      History: JSON.stringify({ entries: [] }),
      "Temporary Device": "",
      SubmittedBy: "testuser@innovationcharter.org",
      FormID: "FORM-DROP",
      "User Description": "Waiting for device to be dropped off.",
      "Device Status": undefined,
      "Temp Status": undefined,
      "Form Name": "Bob Dropper",
      FormEmail: "bob.dropper@example.com",
      FormAsset: "33333",
      Notes: "Awaiting drop-off notes.",
      PrivateNotes: "Private info.",
      "Repair Cost": 0,
      Student: ["stu-333333"],
      Device: ["asset-3"],
      "Temporary Device": "",
      SubmittedBy: "testuser@innovationcharter.org",
      _linked: {
        Device: {
          "Asset Tag": "33333",
          "Device Type": "Chromebook",
          Location: "ICHS - Cart 3",
          // No Status field in Asset type
          _id: "asset-3",
        },
        Student: {
          Name: "Bob Dropper",
          LASID: 333333,
          YOG: "2028",
          Advisor: "Carol Advisor",
          Email: "bob.dropper@example.com",
        },
      },
    },
  },
  {
    name: "Have Device",
    ticket: {
      Created: new Date(2025, 8, 3),
      Number: 10003,
      _id: "havedevice-1",
      "Ticket Status": "Have Device",
      Resolution: "User Education",
      Priority: 2,
      History: JSON.stringify({ entries: [] }),
      "Temporary Device": "",
      SubmittedBy: "testuser@innovationcharter.org",
      FormID: "FORM-HAVE",
      "User Description": "Device is now in possession.",
      "Device Status": "Active",
      "Temp Status": undefined,
      "Form Name": "Charlie Device",
      FormEmail: "charlie.device@example.com",
      FormAsset: "44444",
      Notes: "Device received notes.",
      PrivateNotes: "Private info.",
      "Repair Cost": 0,
      Student: ["stu-444444"],
      Device: ["asset-4"],
      _linked: {
        Device: {
          "Asset Tag": "44444",
          "Device Type": "Chromebook",
          Location: "ICHS - Cart 4",
          // No Status field in Asset type
          _id: "asset-4",
        },
        Student: {
          Name: "Charlie Device",
          LASID: 444444,
          YOG: "2029",
          Advisor: "Dana Advisor",
          Email: "charlie.device@example.com",
        },
      },
    },
  },
  {
    name: "In Repair",
    ticket: {
      Created: new Date(2025, 8, 4),
      Number: 10004,
      _id: "repair-1",
      "Ticket Status": "In Repair",
      Resolution: "User Education",
      Priority: 2,
      History: JSON.stringify({ entries: [] }),
      "Temporary Device": "",
      SubmittedBy: "testuser@innovationcharter.org",
      FormID: "FORM-REPAIR",
      "User Description": "Device is being repaired.",
      "Device Status": "Waiting on Repair",
      "Temp Status": undefined,
      "Form Name": "Dana Repair",
      FormEmail: "dana.repair@example.com",
      FormAsset: "55555",
      Notes: "Repair notes.",
      PrivateNotes: "Private info.",
      "Repair Cost": 50,
      Student: ["stu-555555"],
      Device: ["asset-5"],
      _linked: {
        Device: {
          "Asset Tag": "55555",
          "Device Type": "Chromebook",
          Location: "ICHS - Cart 5",
          // No Status field in Asset type
          _id: "asset-5",
        },
        Student: {
          Name: "Dana Repair",
          LASID: 555555,
          YOG: "2030",
          Advisor: "Eve Advisor",
          Email: "dana.repair@example.com",
        },
      },
    },
  },
  {
    name: "In Progress",
    ticket: {
      Created: new Date(2025, 8, 5),
      Number: 10005,
      _id: "progress-1",
      "Ticket Status": "In Progress",
      Resolution: "User Education",
      Priority: 2,
      History: JSON.stringify({ entries: [] }),
      "Temporary Device": "",
      SubmittedBy: "testuser@innovationcharter.org",
      FormID: "FORM-PROGRESS",
      "User Description": "Ticket is in progress.",
      "Device Status": "Active",
      "Temp Status": undefined,
      "Form Name": "Eve Progress",
      FormEmail: "eve.progress@example.com",
      FormAsset: "66666",
      Notes: "Progress notes.",
      PrivateNotes: "Private info.",
      "Repair Cost": 0,
      Student: ["stu-666666"],
      Device: ["asset-6"],
      _linked: {
        Device: {
          "Asset Tag": "66666",
          "Device Type": "Chromebook",
          Location: "ICHS - Cart 6",
          // No Status field in Asset type
          _id: "asset-6",
        },
        Student: {
          Name: "Eve Progress",
          LASID: 666666,
          YOG: "2031",
          Advisor: "Frank Advisor",
          Email: "eve.progress@example.com",
        },
      },
    },
  },
  {
    name: "Closed",
    ticket: {
      Created: new Date(2025, 8, 6),
      Number: 10006,
      _id: "closed-1",
      "Ticket Status": "Closed",
      Resolution: "Fixed",
      Priority: 2,
      History: JSON.stringify({ entries: [] }),
      "Temporary Device": "",
      SubmittedBy: "testuser@innovationcharter.org",
      FormID: "FORM-CLOSED",
      "User Description": "Ticket is closed.",
      "Device Status": "Retired",
      "Temp Status": undefined,
      "Form Name": "Frank Closed",
      FormEmail: "frank.closed@example.com",
      FormAsset: "77777",
      Notes: "Closed notes.",
      PrivateNotes: "Private info.",
      "Repair Cost": 0,
      Student: ["stu-777777"],
      Device: ["asset-7"],
      _linked: {
        Device: {
          "Asset Tag": "77777",
          "Device Type": "Chromebook",
          Location: "ICHS - Cart 7",
          // No Status field in Asset type
          _id: "asset-7",
        },
        Student: {
          Name: "Frank Closed",
          LASID: 777777,
          YOG: "2032",
          Advisor: "Grace Advisor",
          Email: "frank.closed@example.com",
        },
      },
    },
  },
  {
    name: "Ready for Pickup",
    ticket: {
      Created: new Date(2025, 8, 25),
      Number: 99999,
      _id: "1",
      "Ticket Status": "Ready for Pickup",
      Resolution: "Fixed",
      Priority: 3,
      History: JSON.stringify({ entries: [] }),
      FormID: "FORM-123",
      "User Description": `So my machine was all busted up n stuff`,
      "Device Status": "Active",
      "Temp Status": undefined,
      "Form Name": "John Doe",
      FormEmail: "test.student@innovationcharter.org",
      FormAsset: "11111",
      Notes: "Some public notes on a ticket",
      PrivateNotes: "What is with this kid?",
      "Repair Cost": 0,
      Student: ["stu-123456"],
      Device: ["asset-1"],
      _linked: {
        Device: {
          "Asset Tag": "11111",
          "Device Type": "Chromebook",
          Location: "ICHS - Cart 1",
          _id: "asset-1",
        },
        Student: {
          Name: "John Doe",
          LASID: 123456,
          YOG: "2026",
          Advisor: "Jane Smith",
          Email: "john.doe@innovationcharter.org",
        },
      },
    },
  },
];
